### ISSUE TITLE
服务器单项验证证书过期问题

### ISSUE THREAD

**Issue by ghost** [hengcj/httpsDemo#1]
我看网上说用AFSSLPinningModeCertificate当证书过期之后就不能用了，只能更新证书，建议使用AFSSLPinningModePublicKey

**Comment by windfringe** [comment]
嗯，AFSSLPinningModeCertificate的安全性更高一些，确实会存在证书过期的问题；AFSSLPinningModePublicKey只匹配public key，对应的安全性可能更低一些。
so，看需求吧 :）

**Comment by ghost** [comment]
谢谢
